[build]
  base = "web"
  command = "yarn production"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "14.16.0" 

[[redirects]]
  from = "/admin"
  to = "https://ellebrown.sanity.studio"
  status = 301

[[redirects]]
  from = "/preview/:slug/"
  to = "/.netlify/functions/preview"
  status = 200
  force = true
  _generated_by_eleventy_serverless = "preview"

[[headers]]
  for = "/*"
  [headers.values]
    Basic-Auth = "ellebrown:portfolio"

